### ISSUE TITLE
msix support?

### ISSUE THREAD

**Issue by unikzforce** [0install/0install-win#136]
Hey there guys, do you plan to support windows MSIX?

**Comment by bastianeicher** [comment]
Since MSIX files are technically `.zip` archives it is already possible to create feeds using something like this:

```xml
<implementation arch="Windows-x86_64">
  <command name="run" path="SomeApp.exe"/>
  <archive href="http://example.com/SomeApp_1.2.3_x64.msix" type="application/zip"/>
</implementation>
```

However, this will only work if the app in question does not rely on the "MSIX sandbox" with its registry virtualization features, since Zero Install will simply extract the package and run the executable directly.

@unikzforce Does this help? Do you have some specific use cases or apps you'd like to package for Zero Install?

**Comment by unikzforce** [comment]
Thanks a lot, It is sufficient and awesome
