### ISSUE TITLE
0install overloads Windows 10

### ISSUE THREAD

**Issue by que-vector** [0install/0install-win#180]
Hi,

since I do not know which software is using 0install I write this issue here. Out of nowhere 0install runs hundreds of processes on my windows machine and it seems that I am not the only one:
https://www.computerbase.de/forum/threads/0install-exe-muellt-ram-zu.2112206/

![grafik](https://user-images.githubusercontent.com/69037920/204499871-ebf00862-ef76-4e4e-b369-1b8e7ee13e78.png)

![grafik](https://user-images.githubusercontent.com/69037920/204500713-127eb220-1ed5-4b33-9e5c-4d08072e2941.png)

**Comment by bastianeicher** [comment]
Sorry to hear you're having issues with Zero Install.

Could you look for the log file `%temp%\0install-win %username% Log.txt` and post it here (after removing personally identifiable information such as usernames)? This would help figuring out the cause of the problem.

**Comment by que-vector** [comment]
It seems that this won't help:

C:\Users\XXX>%temp%\0install-win %username% Log.txt
Der Befehl "C:\Users\XXX\AppData\Local\Temp\0install-win" is either misspelled or could not be found.

Do you mean this location?
![grafik](https://user-images.githubusercontent.com/69037920/204552345-059487bf-5a75-4251-aaf6-f1db21f9837f.png)

if yes, then it seems to fit:
![grafik](https://user-images.githubusercontent.com/69037920/204553310-0197c096-0b39-4fd3-815e-cc47ede24508.png)

**Comment by bastianeicher** [comment]
Yes, that's exactly the registry location I was looking for, thanks. :)

You may be able to fix the issue by simply changing the value in the registry to have an upper-case drive letter `D:` instead of `d:`.

Please note that this issue has already been fixed in a newer versions of Zero Install, so this shouldn't occur again if you reinstall on a new machine.

In case this does not solve the issue, you should be able to find the log file by adding apostrophes to the command-line:
```
"%temp%\0install-win %username% Log.txt"
```

**Comment by bastianeicher** [comment]
Hi @que-vector,
just wanted to check in, whether changing the registry value solved the issue for you?
Regards, Bastian

**Comment by que-vector** [comment]
Hi Bastian,
Yes, after the restart, everything worked as it should. 
Thanks a lot!
