### ISSUE TITLE
Ability to do "batch"-like install using GUI for progress reporting when run from command line

### ISSUE THREAD

**Issue by alstrup** [0install/0install-win#88]
We would like to use 0install to seamlessly install applications on behalf of the user using the command line tool without requiring them to do anything, while keeping them informed about what happens.
For this purpose, the "-g" option partially works in the sense it provides a download progress bar in a dialog, but there are a few problems: 

1) It displays a dialog whre the user has to click "Done" to proceed. We would like to skip this skip - i.e. equivalent to what would be a "-y" flag to accept all "safe" options.

2) There are various messages printed to the console, including errors. It would be if there was a flag to cause 0install to report all progress in a dialog.

If we just have part 1, that would help a lot, while part 2 is icing on the cake.

**Comment by bastianeicher** [comment]
Using the command `0install-win` instead of `0install -g` should do what you are looking for:
Unlike the `-g` flag this will not pause at the dialog with the "Done" button. Additionally, `0install-win` is a pure-GUI executable so there is no console output.

Background info:
The differences between `0install -g` and `0install-win` are there in order to match the command-line interface of the Linux version of Zero Install more closely. However, I may change this in a future version, to make it less confusing.

**Comment by alstrup** [comment]
Thanks, awesome. It works like a charm. Thanks a lot for great software!
